performance:
    active: true
    ArrayPrimitive:
        active: true
    CouldBeSequence:
        active: false
        threshold: 3
    ForEachOnRange:
        active: true
        excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**' ]
    SpreadOperator:
        active: true
        excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**' ]
    UnnecessaryPartOfBinaryExpression:
        active: false
    UnnecessaryTemporaryInstantiation:
        active: true
    UnnecessaryTypeCasting:
        active: true
