name: Code Quality Checks

on:
    pull_request:
        branches: [ "dev", "main", "master" ]
        paths:
            - '**/*.kt'
            - '**/*.kts'
            - 'gradle/**'
            - 'gradle.properties'
            - 'settings.gradle.kts'
            - '**/build.gradle.kts'
            - 'build.gradle.kts'
            - 'config/**'
            - '.github/workflows/code_quality_check.yml'

concurrency:
    group: pr-${{ github.event.pull_request.number }}
    cancel-in-progress: true

jobs:
    ktlint_checks:
        name: Check Kotlin code by Ktlint
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'

            - name: Cache Gradle Wrapper
              uses: actions/cache@v4
              with:
                  path: ~/.gradle/wrapper
                  key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v4

            - name: Check Kotlin code
              run: ./gradlew :ktlintCheck

            - name: Save KtLint Report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: ktlint-report
                  path: build/reports/ktlint/

            - name: Save Gradle Problems Report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: gradle-problems-report
                  path: build/reports/problems

            - name: Publish Checkstyle report
              uses: Juuxel/publish-checkstyle-report@v1
              if: ${{ failure() || success() }}
              with:
                  reports: |
                      build/reports/ktlint/*.xml

    detekt_checks:
        name: Check Kotlin code by Detekt
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'

            - name: Cache Gradle Wrapper
              uses: actions/cache@v4
              with:
                  path: ~/.gradle/wrapper
                  key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v4

            - name: Check Kotlin code
              run: ./gradlew :detekt

            - name: Save Detekt Report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: detekt-report
                  path: build/reports/detekt

            - name: Save Gradle Problems Report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: gradle-problems-report
                  path: build/reports/problems

            - name: Publish Checkstyle report
              uses: Juuxel/publish-checkstyle-report@v1
              if: ${{ failure() || success() }}
              with:
                  reports: |
                      build/reports/detekt/*.xml

    android_quality_checks:
        name: Check Android code
        runs-on: ubuntu-latest
        needs:
            - ktlint_checks
            - detekt_checks

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'

            - name: Cache Gradle Wrapper
              uses: actions/cache@v4
              with:
                  path: ~/.gradle/wrapper
                  key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v4

            - name: Android Lint
              run: ./gradlew :app:lintDebug -Dkmp.ios.platforms=none

            - name: Save Android Lint Report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: android-lint-report
                  path: app/build/reports/lint-results-debug.html

    build-ios:
        name: Check iOS compilation
        needs:
            - ktlint_checks
            - detekt_checks
        runs-on: macos-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'

            - name: Cache Gradle Wrapper
              uses: actions/cache@v4
              with:
                  path: ~/.gradle/wrapper
                  key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v4

            - name: Cache Kotlin/Native
              uses: actions/cache@v4
              with:
                  path: ~/.konan
                  key: konan-${{ runner.os }}-${{ hashFiles('**/*.gradle.kts', '**/gradle.properties', '**/settings.gradle.kts') }}
                  restore-keys: |
                      konan-${{ runner.os }}-

            - name: Build iOS Targets
              run: ./gradlew :app:linkDebugFrameworkIosX64

    build-desktop-jvm:
        name: Check Desktop JVM compilation
        needs:
            - ktlint_checks
            - detekt_checks
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'

            - name: Cache Gradle Wrapper
              uses: actions/cache@v4
              with:
                  path: ~/.gradle/wrapper
                  key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v4

            - name: Build iOS Targets
              run: ./gradlew :app:packageDistributionForCurrentOS -Dkmp.ios.platforms=none
